### ISSUE TITLE
Problem generate report

### ISSUE THREAD

**Issue by gustavocearasc** [mahendrapaipuri/grafana-dashboard-reporter-app#43] opened 2024-06-07 14:39 UTC
Hi ,

I have configurate the plugin in grafana, the same is enable , but when I was to test , I received the error message:

{"message":"An error occurred within the plugin","messageId":"plugin.downstreamError","statusCode":500,"traceID":""}

grafana log:

evel=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: failed to receive call resource response: rpc error: code = Unknown desc = grafana app URL not found. Please set it in provisioned config

Any suggestion ?

**Comment by mahendrapaipuri** [comment] 2024-06-09 17:01
Hello @gustavocearasc, You will have to provision the plugin with config and set `appUrl` at which your grafana instance is accessible. Please look in [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#configuring-the-plugin) on how to provision the plugin.

**Comment by DukeSinclair** [comment] 2024-07-25 09:10
i got same error.can you help?

{"message":"Failed to call resource","traceID":""}

**Comment by mahendrapaipuri** [comment] 2024-07-28 07:05
Hey @DukeSinclair, the logs you posted are truncated so there is not a lot of info in them. Could you please enable debug logging and post the logs here to understand the issue you are facing?

Cheers

**Comment by DukeSinclair** [comment] 2024-07-28 08:22
[log.txt](https://github.com/user-attachments/files/16402641/log.txt)


hi..please check this log..thank you

**Comment by mahendrapaipuri** [comment] 2024-07-28 08:38
Thanks for the logs. This is the culprit: `failed to start browser: couldn't create browser context: chrome failed to start:\ncmd_run.go:1129: WARNING: cannot create user data directory: cannot create "/usr/share/grafana/snap/chromium/2910": mkdir /usr/share/grafana/snap/chromium: read-only file system\nneed to run as root or suid\n" traceID=`.

Could you please share the details of your Grafana deployement? Is it running on baremetal or in container? You installed `chromium` from `snap`? Can you try installing `chromium` from `apt` (uninstall the one from `snap` if you choose this option)?

**Comment by DukeSinclair** [comment] 2024-07-28 08:42
i installed on ubuntu 24.04.

following the guide from this [https://forum.mikrotik.com/viewtopic.php?t=193705&sid=89777184dbca535782857d49654aef64#](url)

and install the oss grafana...i already try enterprise version but same error

and i already try apt get install chromium but same error..and i try google chrome also same error.
i try give chmod 777 to the /usr/share/grafana/snap/chromium but got same error

**Comment by mahendrapaipuri** [comment] 2024-07-28 08:48
> and i already try apt get install chromium but same error.

If you are getting the same error even if `apt` installed `chromium`, that means the plugin is still using the chromium installed from `snap`. Can you try removing chromium installed from snap? And then install chromium from `apt`.

**Comment by DukeSinclair** [comment] 2024-07-28 08:53
> > and i already try apt get install chromium but same error.
> 
> If you are getting the same error even if `apt` installed `chromium`, that means the plugin is still using the chromium installed from `snap`. Can you try removing chromium installed from snap? And then install chromium from `apt`.

after removing google chrome and chromium from both snap and apt now i get this error

Error
failed to start browser: couldn't create browser context: exec: "google-chrome": executable file not found in $PATH

can you show me where is the $PATH ?

**Comment by mahendrapaipuri** [comment] 2024-07-28 08:58
Sorry, I wasnt clear enough. You will still need `chromium` for the plugin to work. It is good step that `chromium` is not found on your system. Now please do `sudo apt-get install chromium` and restart Grafana. Let me know if it works for you.

**Comment by DukeSinclair** [comment] 2024-07-28 09:06
> sudo apt-get install chromium

sudo apt-get install chromium
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'chromium-browser' instead of 'chromium'
The following NEW packages will be installed:
  chromium-browser
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/50.0 kB of archives.
After this operation, 105 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package chromium-browser.
(Reading database ... 131202 files and directories currently installed.)
Preparing to unpack .../chromium-browser_2%3a1snap1-0ubuntu2_amd64.deb ...
=> Installing the chromium snap
==> Checking connectivity with the snap store
==> Installing the chromium snap
chromium 126.0.6478.182 from Canonical✓ installed
=> Snap installation complete
Unpacking chromium-browser (2:1snap1-0ubuntu2) ...
Setting up chromium-browser (2:1snap1-0ubuntu2) ...
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
Scanning processes...
Scanning linux images...


after install this same error : 
Error
failed to start browser: couldn't create browser context: chrome failed to start: cmd_run.go:1129: WARNING: cannot create user data directory: cannot create "/usr/share/grafana/snap/chromium/2910": mkdir /usr/share/grafana/snap/chromium: read-only file system need to run as root or suid

i remove it and try install google chrome and then i got 
 err generating report

**Comment by mahendrapaipuri** [comment] 2024-07-28 09:26
Well, seems like Ubuntu is fetching chromium from `snap` anyways. I think we need to fix it on the plugin side to avoid these permission issues.

For a quick fix, can you please do a `ls -la /usr/share/grafana` and share the output here? I guess you should be able to fix it by doing following:

```
rm -rf /usr/share/grafana/snap
mkdir -p /usr/share/grafana/snap
chown -R grafana:grafana /usr/share/grafana/snap
```

Can you try these steps?

**Comment by DukeSinclair** [comment] 2024-07-28 09:34
[log2.txt](https://github.com/user-attachments/files/16402819/log2.txt)

another log

**Comment by mahendrapaipuri** [comment] 2024-07-28 09:40
Again `chromium` stuff. Do you have anything related to `chromium` or `google-chrome` in `/root/.config` or `~/.config`? What is the output of `ls -la /usr/share/grafana`? Are you using `chromium` or `google-chrome`?

**Comment by DukeSinclair** [comment] 2024-07-28 12:55
> Again `chromium` stuff. Do you have anything related to `chromium` or `google-chrome` in `/root/.config` or `~/.config`? What is the output of `ls -la /usr/share/grafana`? Are you using `chromium` or `google-chrome`?

nothing related  

root@snmp:~# ls -la /root/.config
ls: cannot access '/root/.config': No such file or directory
root@snmp:~# grep -r "chromium" /root/.config
grep: /root/.config: No such file or directory
root@snmp:~# grep -r "google-chrome" /root/.config
grep: /root/.config: No such file or directory
root@snmp:~# ls -la ~/.config
ls: cannot access '/root/.config': No such file or directory
root@snmp:~# grep -r "chromium" ~/.config
grep: /root/.config: No such file or directory
root@snmp:~# grep -r "google-chrome" ~/.config
grep: /root/.config: No such file or directory


root@snmp:~# ls -la /usr/share/grafana
total 100
drwxr-xr-x  11 root    root     4096 Jul 28 09:29 .
drwxr-xr-x 138 root    root     4096 Jul 28 09:15 ..
drwxr-xr-x   2 root    root     4096 Jul 24 08:53 bin
drwxr-xr-x   3 root    root     4096 Jul 24 08:53 conf
-rw-r--r--   1 root    root     5426 Dec 18  2023 Dockerfile
drwxr-xr-x   3 root    root     4096 Jul 24 08:53 docs
-rw-r--r--   1 root    root    34523 Dec 18  2023 LICENSE
-rw-r--r--   1 root    root      105 Dec 18  2023 NOTICE.md
drwxr-xr-x   2 root    root     4096 Jul 24 08:53 npm-artifacts
drwxr-xr-x   6 root    root     4096 Jul 24 08:53 packaging
drwxr-xr-x   3 root    root     4096 Jul 24 08:53 plugins-bundled
drwxr-xr-x  17 root    root     4096 Jul 24 08:53 public
-rw-r--r--   1 root    root     3082 Dec 18  2023 README.md
drwxr-xr-x   2 grafana grafana  4096 Jul 28 09:29 snap
drwxr-xr-x   2 root    root     4096 Jul 24 08:53 tools
-rw-r--r--   1 root    root        9 Dec 18  2023 VERSION


im using chromium 

root@snmp:~# dpkg -l | grep chromium
ii  chromium                             126.0.6478.126~linuxmint1+wilma         amd64        web browser

**Comment by DukeSinclair** [comment] 2024-07-28 13:41
i think the problem is with the chromium..if use apt install chromium then it will install snap version..but the snap version cant do the job.

**Comment by mahendrapaipuri** [comment] 2024-07-29 14:54
Actually the error is coming from `grafana-image-renderer` and it says that it cannot launch `chromium` process. I think you will need to clean up all the stale config that has been added to your server by your previous installations of `chromium` and `google-chrome`.

We use RedHat on our prod machines and we installed `chromium` using `yum`. You will have to figure a way to avoid snap version of chromium and see if it helps. 

Try to google on the error you are getting `chrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information` which can give you more leads on what to do next.

**Comment by DukeSinclair** [comment] 2024-07-30 12:16
> chrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information

will retry tomorrow on redhat..i think something wrong with ubuntu

**Comment by mahendrapaipuri** [comment] 2024-08-01 07:15
Great. Thanks for reporting back.

Did you see any errors in the logs about rendering panels? If possible, could you share your dashboard JSON model?

**Comment by DukeSinclair** [comment] 2024-08-04 05:17
> Great. Thanks for reporting back.
> 
> Did you see any errors in the logs about rendering panels? If possible, could you share your dashboard JSON model?

im using 14420 dashboard.if you can test it for the report..and as i check there was no error in the logs..thx

**Closed** 2024-12-24 12:54 UTC
Labels: support
